temp

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,65 +15,70 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Resolve install path
+    - name: vswhere
       shell: powershell
       run: |
-        mkdir ${{ inputs.install-path }} -Force
-        $installPath = Resolve-Path ${{ inputs.install-path }}
-        Add-Content $env:GITHUB_ENV "k3DW_setup_msvc_installPath=$installPath"
+        & %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe
 
-    - name: Cache
-      uses: actions/cache@v5
-      with:
-        path: ${{ env.k3DW_setup_msvc_installPath }}
-        key: temp-key-0003-${{ inputs.vs-version }}
+    # - name: Resolve install path
+    #   shell: powershell
+    #   run: |
+    #     mkdir ${{ inputs.install-path }} -Force
+    #     $installPath = Resolve-Path ${{ inputs.install-path }}
+    #     Add-Content $env:GITHUB_ENV "k3DW_setup_msvc_installPath=$installPath"
 
-    - name: Download and install VS Build Tools, and setup MSVC environment
-      shell: powershell
-      run: |
-        $scriptOutput = python ${{ github.action_path }}/get_install_args.py ${{ inputs.vs-version }} 2>&1
-        if ($LASTEXITCODE -eq 0) {
-          $vsVersion = $scriptOutput[0]
-          $bootstrapper = $scriptOutput[1]
-          $componentID = $scriptOutput[2]
-          Write-Host "Installing Visual Studio $vsVersion at $env:k3DW_setup_msvc_installPath"
-        } else {
-          Write-Host "get_install_args.py failed with exit code: $LASTEXITCODE"
-          Write-Host $scriptOutput
-          exit $LASTEXITCODE
-        }
+    # - name: Cache
+    #   uses: actions/cache@v5
+    #   with:
+    #     path: ${{ env.k3DW_setup_msvc_installPath }}
+    #     key: temp-key-0003-${{ inputs.vs-version }}
 
-        Invoke-Webrequest -Uri $bootstrapper -OutFile vs_buildtools.exe
+    # - name: Download and install VS Build Tools, and setup MSVC environment
+    #   shell: powershell
+    #   run: |
+    #     $scriptOutput = python ${{ github.action_path }}/get_install_args.py ${{ inputs.vs-version }} 2>&1
+    #     if ($LASTEXITCODE -eq 0) {
+    #       $vsVersion = $scriptOutput[0]
+    #       $bootstrapper = $scriptOutput[1]
+    #       $componentID = $scriptOutput[2]
+    #       Write-Host "Installing Visual Studio $vsVersion at $env:k3DW_setup_msvc_installPath"
+    #     } else {
+    #       Write-Host "get_install_args.py failed with exit code: $LASTEXITCODE"
+    #       Write-Host $scriptOutput
+    #       exit $LASTEXITCODE
+    #     }
 
-        Start-Process `
-          -FilePath ".\vs_buildtools.exe" `
-          -ArgumentList @(
-            '--quiet', '--norestart',
-            '--installPath', $env:k3DW_setup_msvc_installPath,
-            '--add', $componentID,
-            '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
-            '--includeRecommended',
-            '--noUpdateInstaller'
-          ) `
-          -NoNewWindow `
-          -Wait
+    #     Invoke-Webrequest -Uri $bootstrapper -OutFile vs_buildtools.exe
 
-        Start-Process `
-          -FilePath ".\vs_buildtools.exe" `
-          -ArgumentList @(
-            '--quiet', '--norestart',
-            '--installPath', $env:k3DW_setup_msvc_installPath,
-            '--add', $componentID,
-            '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
-            '--includeRecommended',
-            '--noUpdateInstaller'
-          ) `
-          -NoNewWindow `
-          -Wait
+    #     Start-Process `
+    #       -FilePath ".\vs_buildtools.exe" `
+    #       -ArgumentList @(
+    #         '--quiet', '--norestart',
+    #         '--installPath', $env:k3DW_setup_msvc_installPath,
+    #         '--add', $componentID,
+    #         '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
+    #         '--includeRecommended',
+    #         '--noUpdateInstaller'
+    #       ) `
+    #       -NoNewWindow `
+    #       -Wait
 
-        rm .\vs_buildtools.exe
+    #     Start-Process `
+    #       -FilePath ".\vs_buildtools.exe" `
+    #       -ArgumentList @(
+    #         '--quiet', '--norestart',
+    #         '--installPath', $env:k3DW_setup_msvc_installPath,
+    #         '--add', $componentID,
+    #         '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
+    #         '--includeRecommended',
+    #         '--noUpdateInstaller'
+    #       ) `
+    #       -NoNewWindow `
+    #       -Wait
 
-        cmd /c "$env:k3DW_setup_msvc_installPath\VC\Auxiliary\Build\vcvars64.bat >nul && set" |
-          ForEach-Object {
-            Add-Content $env:GITHUB_ENV $_
-          }
+    #     rm .\vs_buildtools.exe
+
+    #     cmd /c "$env:k3DW_setup_msvc_installPath\VC\Auxiliary\Build\vcvars64.bat >nul && set" |
+    #       ForEach-Object {
+    #         Add-Content $env:GITHUB_ENV $_
+    #       }
